version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx-test
    restart: unless-stopped
    env_file: .env
    environment:
      - MTX_RTSPTRANSPORTS=tcp
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"