version: "3.8"

services:
  mongodb-local:
    image: mongo:6.0
    container_name: ninesong-mongodb-local
    restart: unless-stopped
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/Public/Documents/NineSong/MongoDB:/data/db
    deploy:
      resources:
        limits:
          memory: 128M